import { ThemeDefinition } from "./types";

export const BUILT_IN_THEMES: Record<string, ThemeDefinition> = {
  "dailys-default": {
    id: "dailys-default",
    name: "Dailys Default",
    colors: {
      background: "#0c0c0c",
      surface: "#141414",
      surfaceElevated: "#1a1a1a",
      foreground: "#f0ede8",
      muted: "rgba(240, 237, 232, 0.38)",
      border: "rgba(240, 237, 232, 0.07)",
      accent: "#d4a853",
      accentSoft: "rgba(212, 168, 83, 0.1)",
      success: "#6fcf8a",
      warning: "#d4a853",
      danger: "#e07070",
      selection: "rgba(212, 168, 83, 0.2)",
      focus: "rgba(212, 168, 83, 0.4)",
    },
    typography: {
      display: "Instrument Serif, serif",
      body: "Inter, sans-serif",
      mono: "JetBrains Mono, monospace",
    },
    shape: {
      radiusSm: 4,
      radiusMd: 10,
      radiusLg: 16,
      borderWidth: 1,
    },
    density: "comfortable",
  },
  "midnight": {
    id: "midnight",
    name: "Midnight",
    colors: {
      background: "#050510",
      surface: "#0b0c1c",
      surfaceElevated: "#151628",
      foreground: "#e2e8f0",
      muted: "#64748b",
      border: "#1e293b",
      accent: "#3b82f6",
      accentSoft: "rgba(59, 130, 246, 0.15)",
      success: "#22c55e",
      warning: "#f59e0b",
      danger: "#ef4444",
      selection: "rgba(59, 130, 246, 0.25)",
      focus: "rgba(59, 130, 246, 0.5)",
    },
    typography: {
      display: "Inter, sans-serif",
      body: "Inter, sans-serif",
      mono: "JetBrains Mono, monospace",
    },
    shape: {
      radiusSm: 6,
      radiusMd: 12,
      radiusLg: 20,
      borderWidth: 1,
    },
    density: "spacious",
  },
  "paper": {
    id: "paper",
    name: "Paper",
    colors: {
      background: "#f4f1ea",
      surface: "#ffffff",
      surfaceElevated: "#fdfdfc",
      foreground: "#1c1917",
      muted: "#78716c",
      border: "#e7e5e4",
      accent: "#ea580c",
      accentSoft: "rgba(234, 88, 12, 0.1)",
      success: "#16a34a",
      warning: "#ca8a04",
      danger: "#dc2626",
      selection: "rgba(234, 88, 12, 0.2)",
      focus: "rgba(234, 88, 12, 0.4)",
    },
    typography: {
      display: "Instrument Serif, serif",
      body: "Inter, sans-serif",
      mono: "JetBrains Mono, monospace",
    },
    shape: {
      radiusSm: 2,
      radiusMd: 4,
      radiusLg: 8,
      borderWidth: 1,
    },
    density: "comfortable",
  },
  "terminal": {
    id: "terminal",
    name: "Terminal",
    colors: {
      background: "#000000",
      surface: "#080808",
      surfaceElevated: "#111111",
      foreground: "#4ade80",
      muted: "#166534",
      border: "#14532d",
      accent: "#22c55e",
      accentSoft: "rgba(34, 197, 94, 0.1)",
      success: "#22c55e",
      warning: "#eab308",
      danger: "#ef4444",
      selection: "rgba(34, 197, 94, 0.3)",
      focus: "rgba(34, 197, 94, 0.5)",
    },
    typography: {
      display: "JetBrains Mono, monospace",
      body: "JetBrains Mono, monospace",
      mono: "JetBrains Mono, monospace",
    },
    shape: {
      radiusSm: 0,
      radiusMd: 0,
      radiusLg: 0,
      borderWidth: 1,
    },
    density: "compact",
  },
  "mono": {
    id: "mono",
    name: "Mono",
    colors: {
      background: "#0a0a0a",
      surface: "#171717",
      surfaceElevated: "#262626",
      foreground: "#f5f5f5",
      muted: "#737373",
      border: "#404040",
      accent: "#ffffff",
      accentSoft: "rgba(255, 255, 255, 0.1)",
      success: "#f5f5f5",
      warning: "#a3a3a3",
      danger: "#737373",
      selection: "rgba(255, 255, 255, 0.2)",
      focus: "rgba(255, 255, 255, 0.4)",
    },
    typography: {
      display: "Inter, sans-serif",
      body: "Inter, sans-serif",
      mono: "JetBrains Mono, monospace",
    },
    shape: {
      radiusSm: 4,
      radiusMd: 8,
      radiusLg: 16,
      borderWidth: 1,
    },
    density: "comfortable",
  },
};

export const getTheme = (id: string): ThemeDefinition => {
  return BUILT_IN_THEMES[id] || BUILT_IN_THEMES["dailys-default"];
};
