/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zuxzxzwkushkvlrqqyqv"

export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eHp4endrdXNoa3ZscnFxeXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyMjYwNjIsImV4cCI6MjEwMzgwMjA2Mn0.2oJBxMO4l0AaOb1yQHGMevX3cKtbWfP-_d-DSk3c4K0"

export const turnstileSiteKey = "0x4AAAAAAEqL5gYUCwG4byQ4"
